### PR TITLE
initializing klog flags (fix for #104)

### LINKED ISSUE #104: exits with error when trying to write to logfile when k8s api is not available and rbac-manager is running in a ro fs
Using `rbac-manager` v0.8.1

We are running `rbac-manager` with `securityContext.readOnlyRootFilesystem: true` in a GKE cluster and when we update the master version or a configuration (of the master), the `rbac-manager` starts to crashloop with errors :

```
Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=1069, ErrCode=NO_ERROR, debug=""
log: exiting because of error: log: cannot create log: open /tmp/rbac-manager.rbac-manager-66c45f4895-5rwrh.unknownuser.log.ERROR.20191112-084947.1: no such file or directory
```

We setup a dirty workaround to use an `emptyDir` for `/tmp` but that would be nice if `rbac-manager` could handle connection to the k8s api in a failsafe manner (or if at least it could avoid trying to log to files when an Error occurs)

### PR DESCRIPTION
**Pull request by lucasreed**
fixes #104

By simply initializing the klog flags, we send their default configuration to any dependency that uses it, which includes logging to stderr instead of a file.

### CODE REVIEW

File: cmd/manager/main.go [hunk 1]
```diff
@@ -18,6 +18,9 @@ package main
 
 import (
 	"flag"
+
+	"k8s.io/klog"
```
Comment (sudermanjr) [inline cmd/manager/main.go]: Nit: There's not really any need for these extra spaces. Normally I try to organize it like so:
```
Builtin Golang Packages

External Packages

Internal Packages
```

But that's not a hard fast rule at all

Comment (lucasreed) [reply cmd/manager/main.go]: It's a good point, and I'm usually a stickler for formatting too. I was thinking a separate PR to do that in all of our go files for the project.

Comment (sudermanjr) [reply cmd/manager/main.go]: Sounds good. Let's merge this then.
